### ISSUE TITLE
latest metricly cli won't start 

### ISSUE THREAD

**Issue by bspindler** [metricly/metricly-cli#24]
> [bspindler@mbp metricly-cli (master)]$ metricly -h
> /usr/local/lib/node_modules/metricly-cli/js/bin/metricly.js:16
>         'Update available ' + chalk_1.default.dim(notifier.update.current) + chalk_1.default.reset(' → ') + chalk_1.default.green(notifier.update.latest),
>                                                                  ^
> 
> TypeError: Cannot read property 'current' of undefined
>     at Object.<anonymous> (/usr/local/lib/node_modules/metricly-cli/js/bin/metricly.js:16:66)
>     at Module._compile (module.js:541:32)
>     at Object.Module._extensions..js (module.js:550:10)
>     at Module.load (module.js:458:32)
>     at tryModuleLoad (module.js:417:12)
>     at Function.Module._load (module.js:409:3)
>     at Module.runMain (module.js:575:10)
>     at run (bootstrap_node.js:352:7)
>     at startup (bootstrap_node.js:144:9)
>     at bootstrap_node.js:467:3

@TheConnMan maybe I did something wrong during the release?

**Comment by TheConnMan** [comment]
No, this works well from the packaged binary, but fails with this error when I install with Node globally. Might be an issue with Chalk installing globally or with the version of Node.
