### ISSUE TITLE
Add ability to create an archive compatible with the install command

### ISSUE THREAD

**Issue by bspindler** [metricly/metricly-cli#32]
Metricly expects a certain archive structure, best to bake it into the cli.  

I propose adding: 
`metricly package archive <file>` 
which would produce a file compatible with the install command added in #31  that uploads it to Metricly.
Then I can see them pulled together in a build pipeline to provide validation, packaging and deployment: 
`metricly package validate`
`metricly package archive <file>`
`metricly package install <file-created-with-archve>`

**Comment by TheConnMan** [comment]
With a convenience command like `metricly package push` which does all three?

**Comment by bspindler** [comment]
Hell yeah!

**Comment by bspindler** [comment]
done!
