### ISSUE TITLE
add command to download EC2 recommendation report. 

### ISSUE THREAD

**Issue by GitZamfir** [metricly/metricly-cli#72]
Similar to the existing functionality of the "metricly report ec2cost" this command would allow the download of the EC2 recommendation report as available in the Metricly/Cloudwatch UI.

**Comment by CryptoPishka** [comment]
[https://github.com/metricly/metricly-cli/pull/74](url) - PR
[https://github.com/metricly/metricly-cli/releases/tag/v0.9.0](url) - Release

New functionality is in Prod, new command is `metricly report ec2recommendation`
